packages:
  - "apps/*"
  - "packages/trpc-swr"
  - "packages/core/core"
  - "packages/core/next"
  - "packages/core/ssg"
  - "packages/core/infinite"
  - "packages/core/_internal"

link-workspace-packages: "deep"
